Feature:: Support for keys without usage flags
SecurityInnovation/PGPy pull request #371
Opened 2021-05-07 17:34 UTC by cravgabo

This works for this issue: [Option to override/ignore flags (like gpg)](https://github.com/SecurityInnovation/PGPy/issues/257)

You only need assign _require_usage_flags as False to you key before call encrypt function

```python
from pgpy import PGPKey
from pgpy import PGPMessage

key, _ = PGPKey.from_file('path/to/key_without_usage_flags.asc')
msg_pgp = PGPMessage.new(msg_to_encrypt)
key._require_usage_flags = False  # This allow ignore the validation
encrypted_phrase = key.encrypt(msg_pgp)
```

2021-06-05 21:33 UTC, StoicLoofah commented
Apologies for poking, but are there any issues with merging this that I can help address? I happen to be in a situation like #257 where I have been given a key with instructions to encrypt with it, but it doesn't have the proper usage flag, and the issuer cannot generate a new key for me.

2021-06-07 13:39 UTC, J-M0 commented
Thank you for poking actually. I'm sorry I haven't taken any action on this yet, I've been busy with other projects. I will be sure to make time this week to review this PR.

2021-06-10 16:55 UTC, J-M0 requested changes
Please be sure to update the docs to describe how to use this new attribute

2021-06-10 16:55 UTC, J-M0 commented on pgpy/decorators.py
> +import six
Please undo any formatting that is not directly related to this feature

2021-06-10 16:55 UTC, J-M0 commented on pgpy/decorators.py
> +                    raise PGPError(warning)
```suggestion
                warning = "Key {keyid:s} does not have the required usage flag {flags:s}".format(**em)
                if key._require_usage_flags:
                    raise PGPError(warning)
                else:
                    logging.warning(warning)
```

2021-07-08 19:38 UTC, J-M0 approved these changes

2021-07-08 19:52 UTC, merged

2021-07-08 19:53 UTC, J-M0 commented
Thanks @cravgabo!

2021-07-28 10:02 UTC, pamarc commented
Thanks for this new feature, it will help a lot. Have you planned a release date yet?

2021-07-28 15:06 UTC, J-M0 commented
Unfortunately I don't have a date at this time. I'm still working on adding type hints to everything and there are a bunch of other features/issues I'd like to deal with before cutting a release. The master branch is pretty stable right now though, so it should be fine to use that in the meantime.

2022-01-07 16:29 UTC, willbeaufoy commented
+1 for releasing this, I just found I needed it in some code, as an interim measure installed directly from github in my requirements.txt.

2022-03-31 13:21 UTC, rahulv1812 commented
is this released.. as I got this error today with the library? any idea how can I bypass this and encrypt my msg?

2022-06-09 11:24 UTC, danielsemerjya commented
@rahulv1812 Did you found any solution?